name: 🧪 Test with My API Key
description: Test the NodeMaven Python SDK with your own API key
title: "[Test Request] Testing with my API key"
labels: ["testing", "community", "api-key-test"]
assignees:
  - imale
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Test NodeMaven Python SDK with Your API Key
        
        Use this form to request testing of the NodeMaven Python SDK with your own API key.
        This will help you verify that everything works with your specific account and requirements.
        
        **What happens when you submit this?**
        1. Our GitHub Actions will run automated tests with your settings
        2. You'll get a detailed report of what works and what doesn't
        3. Any issues will be documented and addressed
        
        **Your API key is secure:**
        - ✅ Only used temporarily for testing
        - ✅ Not stored or logged anywhere
        - ✅ Automatically cleaned up after tests

  - type: input
    id: countries
    attributes:
      label: 🌍 Countries to Test
      description: Which countries would you like to test? (comma-separated)
      placeholder: "us,gb,ca,au"
      value: "us,gb"
    validations:
      required: true

  - type: dropdown
    id: test-type
    attributes:
      label: 🧪 Test Type
      description: What level of testing would you like?
      options:
        - "Basic Connectivity - Quick API and proxy test"
        - "Comprehensive Testing - Full test suite (all 48 tests)"
        - "Mobile Proxies Only - Test mobile proxy functionality"
        - "Custom Configuration - I'll specify details below"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: proxy-types
    attributes:
      label: 🔌 Proxy Types to Test
      description: Which proxy protocols should we test?
      options:
        - "HTTP Only"
        - "SOCKS5 Only" 
        - "Both HTTP and SOCKS5"
      default: 2
    validations:
      required: true

  - type: textarea
    id: custom-requirements
    attributes:
      label: 📋 Custom Requirements (Optional)
      description: Any specific requirements or configurations you want tested?
      placeholder: |
        Example:
        - Test with specific regions (California, New York)
        - Test session persistence with 1 hour TTL
        - Test quality filtering with "high" filter
        - Test specific ISP targeting
      render: markdown

  - type: dropdown
    id: urgency
    attributes:
      label: ⏰ Urgency
      description: How quickly do you need these test results?
      options:
        - "Low - Within a week is fine"
        - "Medium - Within 24-48 hours"
        - "High - Today if possible"
        - "Critical - ASAP (please explain why)"
      default: 0
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 💡 Your Use Case (Optional)
      description: Tell us about your intended use of NodeMaven proxies
      placeholder: |
        This helps us understand your needs better and provide relevant testing.
        
        Example:
        - Web scraping for e-commerce price monitoring
        - Social media automation
        - API testing from different locations
        - Security research
      render: markdown

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Confirmation
      description: Please confirm the following
      options:
        - label: I have a valid NodeMaven API key
          required: true
        - label: I understand the API key will be used only for testing purposes
          required: true
        - label: I'm okay with test results being public in this GitHub issue
          required: true
        - label: I've read the [NodeMaven Terms of Service](https://dashboard.nodemaven.com/terms)
          required: false

  - type: markdown
    attributes:
      value: |
        ## 🔐 How to Provide Your API Key Securely
        
        **After submitting this issue:**
        
        1. **Go to the [Actions tab](../../actions)**
        2. **Click "NodeMaven Python SDK Tests"**
        3. **Click "Run workflow"** (top right)
        4. **Select your test settings:**
           - Test Mode: Choose based on your selection above
           - API Key: Paste your NodeMaven API key
           - Countries: Use the countries you specified above
        5. **Click "Run workflow"**
        
        The workflow will run and post results as a comment on this issue.
        
        ---
        
        **Need help getting your API key?**
        Visit your [NodeMaven Dashboard](https://dashboard.nodemaven.com/profile) to find your API key.
        
        **Questions?**
        Feel free to ask in the comments below! 